import json
import os

DATA_DIR = r"d:\hackathon\data"

VERIFIED_MP4_STREAMS = [
  "https://www.w3schools.com/html/mov_bbb.mp4",
  "https://vjs.zencdn.net/v/oceans.mp4",
  "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
  "https://www.w3schools.com/tags/movie.mp4",
  "https://media.w3.org/2010/05/sintel/trailer.mp4",
  "https://media.w3.org/2010/05/bunny/trailer.mp4",
  "https://media.w3.org/2010/05/video/movie_300.mp4",
  "https://filesamples.com/samples/video/mp4/sample_640x360.mp4",
  "https://filesamples.com/samples/video/mp4/sample_960x540.mp4",
  "https://filesamples.com/samples/video/mp4/sample_1280x720.mp4",
]

reels = []

# Base 16 Reels
base_reels = [
  {
    "reel_id": "R001",
    "video_id": "v_7284910284719284719",
    "title": "Java Developer Meme: When NullPointerException Appears Again",
    "description": "A relatable meme for Java developers about the infamous NullPointerException error. Shows the frustration of debugging NPEs in production Java code.",
    "duration_seconds": 30,
    "category": "Java",
    "topics": ["java", "programming", "debugging", "meme", "software development", "backend"],
    "watch_duration_seconds": 28,
    "watch_percentage": 93,
    "liked": True,
    "shared": False,
    "saved": True,
    "commented": True,
    "comment_sentiment": "positive",
    "rewatched": True,
    "engagement_score": 0.87,
    "educational_value": 0.25,
    "hype_score": 0.05,
    "author_username": "@java_meme_king",
    "author_name": "Dev Humor HQ",
    "hashtags": ["#java", "#programming", "#nullpointerexception", "#backend", "#developer"],
    "music_title": "🎵 Original Sound - Dev Humor Beats",
    "view_count": 1420000,
    "like_count": 184200,
    "share_count": 24100,
    "comment_count": 3820,
    "created_at": "2026-03-12"
  },
  {
    "reel_id": "R002",
    "video_id": "v_7291048201948201948",
    "title": "Day in the Life of a Software Engineer at a Tech Company",
    "description": "A software engineer at a top tech company shares their typical day: morning standup, code reviews, system design discussions, pair programming sessions, and career growth moments.",
    "duration_seconds": 60,
    "category": "Career",
    "topics": ["software engineering", "career", "tech company", "work life", "productivity", "developer lifestyle"],
    "watch_duration_seconds": 58,
    "watch_percentage": 97,
    "liked": True,
    "shared": True,
    "saved": True,
    "commented": True,
    "comment_sentiment": "positive",
    "rewatched": True,
    "engagement_score": 0.95,
    "educational_value": 0.55,
    "hype_score": 0.10,
    "author_username": "@alex_tech_lead",
    "author_name": "Alex Tech Lead",
    "hashtags": ["#softwareengineering", "#dayinthelife", "#techcareer", "#developer", "#coding"],
    "music_title": "🎵 Lo-Fi Chill Beats - Tech Routine",
    "view_count": 3890000,
    "like_count": 452000,
    "share_count": 89000,
    "comment_count": 12400,
    "created_at": "2026-04-05"
  },
  {
    "reel_id": "R003",
    "video_id": "v_7302948102938401928",
    "title": "Coding Interview Joke: Me After Solving the Easy LeetCode Question",
    "description": "Humorous take on coding interview culture. Shows the emotional rollercoaster of technical interviews, LeetCode preparation anxiety, and the relief of solving problems.",
    "duration_seconds": 25,
    "category": "DSA/Career",
    "topics": ["coding interview", "leetcode", "dsa", "technical interview", "career", "humor", "software engineering"],
    "watch_duration_seconds": 24,
    "watch_percentage": 96,
    "liked": True,
    "shared": True,
    "saved": False,
    "commented": True,
    "comment_sentiment": "positive",
    "rewatched": True,
    "engagement_score": 0.89,
    "educational_value": 0.20,
    "hype_score": 0.08,
    "author_username": "@leetcode_grindset",
    "author_name": "LeetCode Grindset",
    "hashtags": ["#leetcode", "#codinginterview", "#dsa", "#faang", "#swehumor"],
    "music_title": "🎵 Intense Boss Battle Music - Easy Problem",
    "view_count": 2150000,
    "like_count": 312000,
    "share_count": 45000,
    "comment_count": 6700,
    "created_at": "2026-02-28"
  },
  {
    "reel_id": "R004",
    "video_id": "v_7314920491029384756",
    "title": "MacBook Pro M3 vs ThinkPad X1 vs ASUS ROG for Developers: Which Should You Buy?",
    "description": "In-depth comparison of developer laptops covering RAM, build quality, battery life, IDE performance, compilation speed, and value for money for software engineers.",
    "duration_seconds": 55,
    "category": "Hardware",
    "topics": ["laptop", "macbook", "thinkpad", "developer hardware", "productivity", "software engineering tools", "hardware"],
    "watch_duration_seconds": 50,
    "watch_percentage": 91,
    "liked": True,
    "shared": False,
    "saved": True,
    "commented": False,
    "comment_sentiment": "neutral",
    "rewatched": False,
    "engagement_score": 0.76,
    "educational_value": 0.50,
    "hype_score": 0.15,
    "author_username": "@dev_hardware_reviews",
    "author_name": "DevHardware Lab",
    "hashtags": ["#macbook", "#thinkpad", "#developerhardware", "#laptopreview", "#productivity"],
    "music_title": "🎵 Tech Unboxing Ambient Beat",
    "view_count": 980000,
    "like_count": 87000,
    "share_count": 14200,
    "comment_count": 2100,
    "created_at": "2026-03-18"
  },
  {
    "reel_id": "R005",
    "video_id": "v_7325910293847561928",
    "title": "How RAG Systems Retrieve Documents Before Generating an Answer",
    "description": "Technical deep-dive into Retrieval Augmented Generation. Explains vector embeddings, semantic search, document retrieval pipeline, and how retrieved context improves LLM output quality.",
    "duration_seconds": 58,
    "category": "AI",
    "topics": ["rag", "retrieval augmented generation", "llm", "vector embeddings", "ai", "machine learning", "nlp", "generative ai"],
    "watch_duration_seconds": 55,
    "watch_percentage": 95,
    "liked": True,
    "shared": True,
    "saved": True,
    "commented": True,
    "comment_sentiment": "positive",
    "rewatched": True,
    "engagement_score": 0.96,
    "educational_value": 0.95,
    "hype_score": 0.03,
    "author_username": "@ai_explainer",
    "author_name": "AI Explained Simply",
    "hashtags": ["#ai", "#rag", "#llm", "#machinelearning", "#generativeai"],
    "music_title": "🎵 Futuristic Synthwave - Deep Tech",
    "view_count": 1850000,
    "like_count": 240000,
    "share_count": 67000,
    "comment_count": 8900,
    "created_at": "2026-05-01"
  },
  {
    "reel_id": "R006",
    "video_id": "v_7336928475610293847",
    "title": "Valorant Pro Player Insane Clutch 1v5 — Highlights Compilation",
    "description": "Professional Valorant gameplay highlights featuring expert tactics, reflexes, and team coordination.",
    "duration_seconds": 45,
    "category": "Gaming",
    "topics": ["gaming", "valorant", "esports", "entertainment", "fps game", "competitive gaming"],
    "watch_duration_seconds": 22,
    "watch_percentage": 49,
    "liked": False,
    "shared": False,
    "saved": False,
    "commented": False,
    "comment_sentiment": "neutral",
    "rewatched": False,
    "engagement_score": 0.25,
    "educational_value": 0.03,
    "hype_score": 0.20,
    "author_username": "@esports_clutches",
    "author_name": "Esports Highlights",
    "hashtags": ["#valorant", "#gaming", "#esports", "#clutch", "#gamer"],
    "music_title": "🎵 EDM Trap Remix - Gaming Hype",
    "view_count": 5400000,
    "like_count": 680000,
    "share_count": 120000,
    "comment_count": 15400,
    "created_at": "2026-01-15"
  },
  {
    "reel_id": "R007",
    "video_id": "v_7347019283746510293",
    "title": "10 AI Tools That Will Guarantee You a Job in 2024",
    "description": "Clickbait listicle claiming that using 10 specific AI tools guarantees employment. Promotes superficial tool usage without explaining underlying concepts or skills.",
    "duration_seconds": 40,
    "category": "AI Hype",
    "topics": ["ai tools", "job guarantee", "career hack", "chatgpt", "automation"],
    "watch_duration_seconds": 12,
    "watch_percentage": 30,
    "liked": False,
    "shared": False,
    "saved": False,
    "commented": False,
    "comment_sentiment": "neutral",
    "rewatched": False,
    "engagement_score": 0.15,
    "educational_value": 0.05,
    "hype_score": 0.95,
    "author_username": "@get_rich_ai_hacks",
    "author_name": "AI Career Hacks 101",
    "hashtags": ["#aitools", "#jobhacks", "#chatgpt", "#careeradvice", "#getrich"],
    "music_title": "🎵 Fast Energetic Pop - Clickbait Vibe",
    "view_count": 4200000,
    "like_count": 190000,
    "share_count": 54000,
    "comment_count": 8900,
    "created_at": "2026-02-10"
  },
  {
    "reel_id": "R008",
    "video_id": "v_7358102938475619203",
    "title": "How a Backend Request Travels Through Load Balancer, API Gateway, Cache and Database",
    "description": "Educational system design walkthrough of a production backend request lifecycle. Covers load balancing algorithms, API gateway patterns, Redis caching strategies, and database connection pooling.",
    "duration_seconds": 60,
    "category": "HLD",
    "topics": ["system design", "backend", "load balancer", "api gateway", "database", "cache", "redis", "cloud", "software engineering", "hld"],
    "watch_duration_seconds": 57,
    "watch_percentage": 95,
    "liked": True,
    "shared": True,
    "saved": True,
    "commented": True,
    "comment_sentiment": "positive",
    "rewatched": True,
    "engagement_score": 0.96,
    "educational_value": 0.95,
    "hype_score": 0.02,
    "author_username": "@system_design_guru",
    "author_name": "System Design Guru",
    "hashtags": ["#systemdesign", "#backend", "#loadbalancer", "#redis", "#softwareengineering"],
    "music_title": "🎵 Architectural Deep Learning Soundtrack",
    "view_count": 2900000,
    "like_count": 380000,
    "share_count": 92000,
    "comment_count": 11200,
    "created_at": "2026-05-18"
  },
  {
    "reel_id": "R009",
    "video_id": "v_7369201837465192837",
    "title": "OWASP Top 10 Security Vulnerabilities: SQL Injection Live Demo",
    "description": "Live demonstration of how unparsed user inputs lead to SQL injection vulnerabilities in backend Node/Python apps and how parameterized queries eliminate the attack vector.",
    "duration_seconds": 50,
    "category": "Cybersecurity",
    "topics": ["cybersecurity", "web security", "sqlinjection", "owasp", "ethical hacking", "backend"],
    "watch_duration_seconds": 48,
    "watch_percentage": 96,
    "liked": True,
    "shared": True,
    "saved": True,
    "commented": True,
    "comment_sentiment": "positive",
    "rewatched": True,
    "engagement_score": 0.94,
    "educational_value": 0.92,
    "hype_score": 0.03,
    "author_username": "@sec_ninja",
    "author_name": "CyberSec Labs",
    "hashtags": ["#cybersecurity", "#sqlinjection", "#owasp", "#ethicalhacking", "#websecurity"],
    "music_title": "🎵 Dark Hacker Synth - Cyber Security",
    "view_count": 1650000,
    "like_count": 210000,
    "share_count": 48000,
    "comment_count": 5900,
    "created_at": "2026-06-02"
  },
  {
    "reel_id": "R010",
    "video_id": "v_7370319284756192837",
    "title": "Docker vs Kubernetes in 60 Seconds: Containers vs Orchestration",
    "description": "Clear visual comparison explaining why Docker packs your code into a container while Kubernetes manages hundreds of those containers across server clusters.",
    "duration_seconds": 60,
    "category": "Cloud",
    "topics": ["docker", "kubernetes", "cloud", "devops", "containerization", "backend"],
    "watch_duration_seconds": 56,
    "watch_percentage": 93,
    "liked": True,
    "shared": True,
    "saved": True,
    "commented": True,
    "comment_sentiment": "positive",
    "rewatched": True,
    "engagement_score": 0.92,
    "educational_value": 0.90,
    "hype_score": 0.04,
    "author_username": "@devops_pro",
    "author_name": "DevOps Classroom",
    "hashtags": ["#docker", "#kubernetes", "#devops", "#cloudcomputing", "#backend"],
    "music_title": "🎵 Upbeat Tech Explanation Groove",
    "view_count": 2400000,
    "like_count": 310000,
    "share_count": 75000,
    "comment_count": 9400,
    "created_at": "2026-05-24"
  },
  {
    "reel_id": "R011",
    "video_id": "v_7381420583920184758",
    "title": "React 19 Server Components vs Client Components in 60 Seconds",
    "description": "Visual breakdown of React 19 Server Components rendering on the server vs Interactive Client Components with useActionState hooks.",
    "duration_seconds": 52,
    "category": "Frontend",
    "topics": ["react", "react19", "frontend", "javascript", "webdev", "components"],
    "watch_duration_seconds": 50,
    "watch_percentage": 96,
    "liked": True,
    "shared": True,
    "saved": True,
    "commented": True,
    "comment_sentiment": "positive",
    "rewatched": True,
    "engagement_score": 0.94,
    "educational_value": 0.91,
    "hype_score": 0.03,
    "author_username": "@react_pro_tips",
    "author_name": "React Mastery Lab",
    "hashtags": ["#reactjs", "#frontend", "#javascript", "#webdev", "#react19"],
    "music_title": "🎵 Upbeat Frontend Code Beats",
    "view_count": 3100000,
    "like_count": 420000,
    "share_count": 86000,
    "comment_count": 9800,
    "created_at": "2026-06-10"
  },
  {
    "reel_id": "R012",
    "video_id": "v_7392531694031295869",
    "title": "Why Rust Borrow Checker Prevents Memory Leaks and Data Races",
    "description": "How Rust's ownership rules and borrow checker guarantee memory safety without a garbage collector overhead.",
    "duration_seconds": 58,
    "category": "Systems",
    "topics": ["rust", "systems programming", "memory safety", "cpp", "concurrency"],
    "watch_duration_seconds": 56,
    "watch_percentage": 96,
    "liked": True,
    "shared": True,
    "saved": True,
    "commented": True,
    "comment_sentiment": "positive",
    "rewatched": True,
    "engagement_score": 0.95,
    "educational_value": 0.94,
    "hype_score": 0.02,
    "author_username": "@rust_systems_lab",
    "author_name": "Rust Systems Lab",
    "hashtags": ["#rust", "#systems", "#memorysafety", "#cpp", "#programming"],
    "music_title": "🎵 High-Speed Systems Programming Beats",
    "view_count": 1980000,
    "like_count": 270000,
    "share_count": 59000,
    "comment_count": 7200,
    "created_at": "2026-06-15"
  },
  {
    "reel_id": "R013",
    "video_id": "v_7403642705142306970",
    "title": "Transformer Self-Attention Mechanism Explained Visually",
    "description": "Step-by-step visual matrix multiplication walkthrough showing Query, Key, and Value matrices in Transformer attention layers.",
    "duration_seconds": 60,
    "category": "AI",
    "topics": ["transformers", "attention mechanism", "ai", "deep learning", "nlp", "llm"],
    "watch_duration_seconds": 58,
    "watch_percentage": 96,
    "liked": True,
    "shared": True,
    "saved": True,
    "commented": True,
    "comment_sentiment": "positive",
    "rewatched": True,
    "engagement_score": 0.97,
    "educational_value": 0.98,
    "hype_score": 0.02,
    "author_username": "@ml_deep_learning",
    "author_name": "Deep Learning Visualized",
    "hashtags": ["#machinelearning", "#transformers", "#ai", "#deeplearning", "#nlp"],
    "music_title": "🎵 Neural Network Ambient Synth",
    "view_count": 2750000,
    "like_count": 390000,
    "share_count": 91000,
    "comment_count": 10500,
    "created_at": "2026-06-20"
  },
  {
    "reel_id": "R014",
    "video_id": "v_7414753816253417081",
    "title": "Python AsyncIO vs Threading: Handling 10,000 Concurrent Connections",
    "description": "Benchmark comparison of Python AsyncIO event loop vs Multithreading for high-concurrency I/O bound web applications.",
    "duration_seconds": 55,
    "category": "Backend",
    "topics": ["python", "asyncio", "concurrency", "backend", "fastapi", "performance"],
    "watch_duration_seconds": 53,
    "watch_percentage": 96,
    "liked": True,
    "shared": True,
    "saved": True,
    "commented": True,
    "comment_sentiment": "positive",
    "rewatched": True,
    "engagement_score": 0.93,
    "educational_value": 0.91,
    "hype_score": 0.03,
    "author_username": "@python_mastery",
    "author_name": "Python Backend Lab",
    "hashtags": ["#python", "#asyncio", "#concurrency", "#backend", "#fastapi"],
    "music_title": "🎵 Async Event Loop Groove",
    "view_count": 1820000,
    "like_count": 230000,
    "share_count": 47000,
    "comment_count": 6100,
    "created_at": "2026-06-25"
  },
  {
    "reel_id": "R015",
    "video_id": "v_7425864927364528192",
    "title": "PostgreSQL Query Optimization: How EXPLAIN ANALYZE Finds Slow Scans",
    "description": "How to inspect query execution plans, identify sequential table scans, and build composite B-Tree indexes in PostgreSQL.",
    "duration_seconds": 58,
    "category": "Backend",
    "topics": ["postgres", "sql", "database", "backend", "performance optimization", "indexing"],
    "watch_duration_seconds": 55,
    "watch_percentage": 95,
    "liked": True,
    "shared": True,
    "saved": True,
    "commented": True,
    "comment_sentiment": "positive",
    "rewatched": True,
    "engagement_score": 0.94,
    "educational_value": 0.93,
    "hype_score": 0.02,
    "author_username": "@database_pro",
    "author_name": "SQL & Postgres Master",
    "hashtags": ["#postgres", "#sql", "#database", "#backend", "#performance"],
    "music_title": "🎵 Database Query Beats",
    "view_count": 1540000,
    "like_count": 195000,
    "share_count": 42000,
    "comment_count": 5100,
    "created_at": "2026-07-01"
  },
  {
    "reel_id": "R016",
    "video_id": "v_7436975038475639203",
    "title": "Microservices Distributed Tracing with OpenTelemetry and Jaeger",
    "description": "How context propagation headers trace HTTP/gRPC requests across microservices clusters to pinpoint latency bottlenecks.",
    "duration_seconds": 60,
    "category": "Cloud",
    "topics": ["microservices", "opentelemetry", "observability", "devops", "cloud", "backend"],
    "watch_duration_seconds": 57,
    "watch_percentage": 95,
    "liked": True,
    "shared": True,
    "saved": True,
    "commented": True,
    "comment_sentiment": "positive",
    "rewatched": True,
    "engagement_score": 0.95,
    "educational_value": 0.92,
    "hype_score": 0.03,
    "author_username": "@cloud_observability",
    "author_name": "DevOps & Cloud Lab",
    "hashtags": ["#microservices", "#opentelemetry", "#observability", "#devops", "#cloud"],
    "music_title": "🎵 Distributed Systems Soundtrack",
    "view_count": 2100000,
    "like_count": 280000,
    "share_count": 64000,
    "comment_count": 7800,
    "created_at": "2026-07-05"
  }
]

# Generate R017 to R050 programmatically with rich tech content topics!
extra_topics_data = [
    ("Spring Boot 3.2 Virtual Threads Performance Benchmark", "Java", ["java", "spring boot", "virtual threads", "concurrency", "backend"], 0.94, 0.02, "@spring_guru"),
    ("JVM Garbage Collection Internals: ZGC vs G1GC in Production", "Java", ["java", "jvm", "garbage collection", "performance", "backend"], 0.95, 0.01, "@jvm_internals"),
    ("Java Memory Model Explained: Happens-Before Relationship", "Java", ["java", "concurrency", "multithreading", "memory model", "backend"], 0.93, 0.02, "@java_concurrency"),
    ("FastAPI Dependency Injection for Enterprise Microservices", "Python", ["python", "fastapi", "dependency injection", "microservices", "backend"], 0.92, 0.03, "@fastapi_daily"),
    ("Python Pydantic v2 Rust Core Validation Speedup Walkthrough", "Python", ["python", "pydantic", "rust", "validation", "fastapi"], 0.91, 0.02, "@python_devs"),
    ("Fine-Tuning Llama-3 with LoRA and QLoRA on a Single GPU", "AI", ["lora", "qlora", "fine tuning", "llama3", "generative ai", "llm"], 0.97, 0.03, "@llm_architect"),
    ("Vector Database Internals: HNSW Graph Indexing vs IVF", "AI", ["vector database", "hnsw", "chromadb", "faiss", "ai", "rag"], 0.96, 0.02, "@vector_db_pro"),
    ("Building Agentic Workflows with LangGraph and ReAct Pattern", "AI", ["agentic ai", "langgraph", "langchain", "agents", "ai"], 0.98, 0.04, "@ai_agent_lab"),
    ("LLM Context Window Management: Needle in a Haystack Test", "AI", ["llm", "context window", "prompt engineering", "ai", "nlp"], 0.95, 0.03, "@llm_eval"),
    ("Designing a Distributed Rate Limiter with Token Bucket Algorithm", "HLD", ["system design", "rate limiter", "redis", "token bucket", "hld"], 0.96, 0.02, "@sysdesign_daily"),
    ("Kafka Architecture: Topics, Partitions, Consumer Groups and ISR", "HLD", ["kafka", "event streaming", "distributed systems", "hld", "backend"], 0.97, 0.01, "@event_streaming"),
    ("Database Sharding vs Partitioning: Scaling Relational DBs to 100M Users", "HLD", ["database", "sharding", "scalability", "sql", "hld"], 0.96, 0.02, "@scale_db"),
    ("Consistent Hashing in Distributed Caching Systems", "HLD", ["consistent hashing", "cache", "memcached", "redis", "hld"], 0.95, 0.02, "@distributed_lab"),
    ("Kubernetes Custom Resource Definitions (CRDs) and Operator Pattern", "Cloud", ["kubernetes", "crd", "operator pattern", "go", "cloud"], 0.94, 0.03, "@k8s_operator"),
    ("Terraform Infrastructure as Code: State Locking and Remote Backends", "Cloud", ["terraform", "iac", "devops", "aws", "cloud"], 0.92, 0.02, "@terraform_pro"),
    ("Docker Multi-Stage Builds: Reducing Image Size from 1GB to 25MB", "Cloud", ["docker", "containers", "devops", "ci/cd", "cloud"], 0.93, 0.02, "@docker_tips"),
    ("JWT Authentication vs Session Tokens: Security Trade-offs", "Cybersecurity", ["jwt", "security", "authentication", "web security", "owasp"], 0.91, 0.04, "@auth_security"),
    ("Cross-Site Scripting (XSS) Prevention in Modern Web Apps", "Cybersecurity", ["xss", "web security", "owasp", "csp", "cybersecurity"], 0.93, 0.02, "@appsec_daily"),
    ("Trie Data Structure: Implementing Autocomplete in O(K) Time", "DSA", ["dsa", "trie", "algorithms", "leetcode", "data structures"], 0.94, 0.02, "@dsa_master"),
    ("Dijkstra vs A* Search Algorithm Visualized on Grid Maps", "DSA", ["dsa", "graph algorithms", "dijkstra", "leetcode", "algorithms"], 0.96, 0.02, "@algo_visualizer"),
    ("Dynamic Programming: 5-Step Framework to Master Memoization", "DSA", ["dsa", "dynamic programming", "leetcode", "algorithms", "coding interview"], 0.95, 0.03, "@dp_grind"),
    ("LRU Cache Implementation using Doubly Linked List and Hash Map", "DSA", ["dsa", "lru cache", "data structures", "leetcode", "coding interview"], 0.96, 0.02, "@dsa_patterns"),
    ("React 19 useActionState and Optimistic Updates Guide", "Frontend", ["react", "frontend", "hooks", "javascript", "webdev"], 0.92, 0.03, "@react_tricks"),
    ("CSS Container Queries vs Media Queries for Component Design", "Frontend", ["css", "frontend", "responsive design", "webdev", "ui"], 0.89, 0.04, "@css_wizardry"),
    ("TypeScript 5.4 Const Type Parameters and Utility Types", "Frontend", ["typescript", "javascript", "frontend", "webdev", "type safety"], 0.93, 0.02, "@ts_pro"),
    ("Rust Tokio Async Runtime Mechanics: Tasks, Channels and Select", "Systems", ["rust", "tokio", "async", "systems", "concurrency"], 0.96, 0.02, "@rust_tokio"),
    ("C++20 Coroutines and Concepts for Modern Systems Engineers", "Systems", ["cpp", "cpp20", "coroutines", "systems programming", "c++"], 0.95, 0.02, "@cpp_mastery"),
    ("Best FPS Mouse Sensitivity Settings for Valorant Competitive", "Gaming", ["gaming", "valorant", "fps", "esports", "aiming"], 0.15, 0.35, "@gamer_aim_lab"),
    ("CS2 Insane Ninja Defuse 1v4 Clutch", "Gaming", ["gaming", "cs2", "esports", "counterstrike", "entertainment"], 0.10, 0.40, "@clutch_nation"),
    ("Top 5 AI Hacks to Make $10,000 a Month Side Hustle", "AI Hype", ["ai tools", "side hustle", "get rich", "ai prompts"], 0.05, 0.98, "@hustle_ai_hacks"),
    ("Automatic Code Writing with 1 Click — No Coding Required!", "AI Hype", ["ai coding", "no code", "instant app", "ai hype"], 0.04, 0.99, "@nocode_hype"),
    ("Master System Design in 10 Minutes with This Simple Trick", "Career Hype", ["system design", "cheat sheet", "shortcut", "career hack"], 0.08, 0.90, "@career_shortcuts"),
    ("Why Senior Developers Never Write Unit Tests Anymore", "Career Hype", ["unit tests", "developer debate", "clickbait", "swe"], 0.05, 0.92, "@dev_hot_takes"),
    ("Build a Full Stack SaaS App in 5 Minutes using AI", "AI Hype", ["saas", "ai app", "5 minutes", "clickbait"], 0.06, 0.96, "@instant_saas"),
]

for idx, (title, category, topics, edu_val, hype_val, author) in enumerate(extra_topics_data, start=17):
    reel_id = f"R{idx:03d}"
    video_id = f"v_7448{idx:04d}90123"
    stream_url = VERIFIED_MP4_STREAMS[(idx - 1) % len(VERIFIED_MP4_STREAMS)]
    
    is_hype = hype_val > 0.60
    is_gaming = category == "Gaming"
    
    reels.append({
        "reel_id": reel_id,
        "video_id": video_id,
        "video_url": stream_url,
        "title": title,
        "description": f"Short-form technical educational Reel explaining {title}. Targeted at software engineering and technology learners.",
        "duration_seconds": 50 + (idx % 15),
        "category": category,
        "topics": topics,
        "watch_duration_seconds": 15 if (is_hype or is_gaming) else 48,
        "watch_percentage": 30 if (is_hype or is_gaming) else 94,
        "liked": False if (is_hype or is_gaming) else True,
        "shared": False if (is_hype or is_gaming) else True,
        "saved": False if (is_hype or is_gaming) else True,
        "commented": False if (is_hype or is_gaming) else True,
        "comment_sentiment": "negative" if is_hype else ("positive" if not is_gaming else "neutral"),
        "rewatched": False if (is_hype or is_gaming) else True,
        "engagement_score": 0.20 if (is_hype or is_gaming) else 0.94,
        "educational_value": edu_val,
        "hype_score": hype_val,
        "author_username": author,
        "author_name": author.replace("@", "").replace("_", " ").title(),
        "hashtags": [f"#{t.replace(' ', '')}" for t in topics[:4]],
        "music_title": f"🎵 Tech Beats - {category} Learning",
        "view_count": 1200000 + (idx * 50000),
        "like_count": 150000 + (idx * 4000),
        "share_count": 30000 + (idx * 1000),
        "comment_count": 4000 + (idx * 200),
        "created_at": "2026-07-15"
    })

all_reels = base_reels + reels
all_reel_ids = [r["reel_id"] for r in all_reels]

# Load existing sample_reels.json to preserve users and suggested accounts
with open(os.path.join(DATA_DIR, "sample_reels.json"), "r", encoding="utf-8") as f:
    data = json.load(f)

data["reels"] = all_reels
data["dataset_metadata"]["description"] = f"Comprehensive short-form video dataset containing {len(all_reels)} tech Reels backed by verified, fast-loading HTML5 MP4 video streams, interaction signals, engagement metrics, hashtags, audio metadata, and tech/career content topics."

# Update student profiles with 50 reels
data["student_profiles"] = [
    {
      "profile_id": "P001",
      "name": "Alex — The Aspiring Software Engineer",
      "description": "Watches Java memes, career content, interview humor, and laptop comparisons. Classic Java Trap profile.",
      "reel_ids": ["R001", "R002", "R003", "R004", "R008", "R011", "R014", "R015", "R017", "R018", "R019", "R026", "R027", "R028", "R029"]
    },
    {
      "profile_id": "P002",
      "name": "Priya — The AI Enthusiast",
      "description": "Deeply engaged with AI/ML educational content. High completion rates on technical content.",
      "reel_ids": ["R005", "R008", "R010", "R002", "R013", "R012", "R015", "R016", "R022", "R023", "R024", "R025", "R030", "R031", "R042"]
    },
    {
      "profile_id": "P003",
      "name": "Sam — The Entertainment Consumer",
      "description": "Primarily watches gaming and entertainment content. Low engagement with tech content.",
      "reel_ids": ["R006", "R007", "R001", "R044", "R045", "R046", "R047"]
    },
    {
      "profile_id": "P004",
      "name": "TikTok-10M Feed — Real-Time Scrolling Feed",
      "description": "Interactive vertical scrolling reel feed powered by TikTok-10M dataset signals.",
      "reel_ids": all_reel_ids
    }
]

with open(os.path.join(DATA_DIR, "sample_reels.json"), "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2)

print(f"Successfully generated {len(all_reels)} Reels in sample_reels.json!")
